on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository_owner }}/frontend
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
jobs:
    Unit-Testing:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '16'
            cache: 'npm'
        - name: Run tests
          run: App.test.js