on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository_owner }}/frontend
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    

jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: List installed node modules (Debug)
        run: ls node_modules

      - name: Debug react-scripts installation (Debug)
        run: npm list react-scripts

      - name: Run tests
        run: npm test

      - name: Check npm cache (Debug)
        run: npm cache verify